### ISSUE TITLE
An option to limit expac to search only specified repos via -S.

### ISSUE THREAD

**Issue by Earnestly** [falconindy/expac#24] opened 2015-09-13 18:18 UTC
This is related to issue #23.

I would like to limit expac to search only specific repositories when
specifying `-S`.

As a work around for this I am instead prefixing the repo name (`%r`) and using
that as a marker for awk which then prints the remaining column.  E.g.

``` sh
expac -S '%r %n:%E' -l ':' < <(pacman -Sql "$repo") | awk -v repo="^$repo" '$1 ~ repo { print $2 }'
```

Ideally I would like to constrain `-S` to the defined `$repo` above via
something like `expac -S --repo=$repo ...`.

Any thoughts?

**Comment by AladW** [comment] 2016-04-19 10:23
Actually you can do this already by specifying the repo name to expac with `repo/package` pairs. So in case the same package names are in several repos, this would work in theory:
```
pacman -Sl core --print-format='%r/%n' | expac -S '%n %E' -
```
However, `--print-format` doesn't work with `--list` for some reason. `pacsift` does work:
```
pacsift --exact --repo="$1" | expac -S '%n %E' -
```
Also note the `-` after expac so it takes values from stdin, rather than print every sync package.

**Comment by Earnestly** [comment] 2016-04-19 14:16
Oh that's nice.  `pacsift` is quite useful here.  I've switched to this for the `repo-cycle-detector` instead.

Thanks

**Comment by andrewgregory** [comment] 2016-04-19 20:11
I'm not sure what you think having pacsift return non-zero would do here.  If you use expac in a pipe it will run regardless of what pacsift returns.  What needs to happen is that expac needs to be changed to not fallback to all packages when `-` is given with empty `stdin`.

**Comment by Earnestly** [comment] 2016-04-19 20:16
Sorry, I didn't mean to talk about return values, I'm being a bit of a derp lately.  Yes you're exactly right, if `expac ... /dev/stdin` or `expac ... -` is used it shouldn't fallback to all packages.

**Comment by AladW** [comment] 2016-05-02 13:45
For the stdin issue, see #29

**Comment by falconindy** [comment] 2016-05-02 17:47
So this is basically a dupe of #29? Or is there something else that needs to be addressed?

**Closed** 2024-08-01 20:27 UTC
